#! /bin/sh

FGCOLOR="#ad5156"
BGCOLOR="#181818"

bspc config border_width        2
bspc config window_gap          14
bspc config top_padding			14

bspc config split_ratio         0.50
bspc config borderless_monocle  false
bspc config gapless_monocle     false 
bspc config focus_by_distance   true

bspc config focused_border_color $FGCOLOR
bspc config active_border_color $FGCOLOR
bspc config normal_border_color $BGCOLOR
bspc config urgent_border_color $FGCOLOr

bspc normal_frame_opacity 0.00
bspc focused_frame_opacity 1.00
bspc config focus_follows_pointer true

COUNT="$(xrandr -d :0 -q | grep ' connected' | wc -l)"

if [ $COUNT -eq 2 ]
	then	
		bspc monitor VGA-0 -d I II III IV V
		bspc monitor LVDS-0 -d VI VII VIII IX X
	else
		bspc monitor LVDS-0 -d I II III IV V VI VII VIII IX X
	fi


bspc rule -a guake floating=on
bspc rule -a galculator floating=on
bspc rule -a gpick floating=off
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
