#! /bin/sh

FGCOLOR="#a7b9d3"
BGCOLOR="#121218"

COUNT="$(xrandr -d :0 -q | grep ' connected' | wc -l)"

if [ $COUNT -eq 2 ]
	then	
		bspc monitor LVDS-0 -d I II III IV V
		bspc monitor HDMI-0 -d VI VII VIII IX X
	else
		bspc monitor LVDS-0 -d I II III IV V VI VII VIII IX X
	fi

bspc config border_width        4
bspc config top_padding		29
bspc config bottom_padding	0
bspc config window_gap          32

bspc config split_ratio         0.5
bspc config borderless_monocle  false
bspc config gapless_monocle     false 

bspc config focused_border_color $FGCOLOR
bspc config active_border_color $FGCOLOR
bspc config normal_border_color $BGCOLOR

bspc config focus_follows_pointer true

bspc rule -a vis state=floating sticky=on focus=off locked=on private=on
