#! /bin/sh

FGCOLOR="#f5c56b"
BGCOLOR="#2f2526"

bspc config border_width        1
bspc config window_gap          8

bspc config split_ratio         0.50
bspc config borderless_monocle  false
bspc config gapless_monocle     false 
bspc config focus_by_distance   true

bspc config bottom_padding	16

bspc config focused_border_color $FGCOLOR
bspc config active_border_color $FGCOLOR
bspc config normal_border_color $BGCOLOR
bspc config urgent_border_color $FGCOLOr

baspc normal_frame_opacity 0.00
bspc focused_frame_opacity 1.00
bspc config focus_follows_pointer true

COUNT="$(xrandr -d :0 -q | grep ' connected' | wc -l)"

if [ $COUNT -eq 2 ]
	then	
		bspc monitor VGA-0 -d I II III IV V
		bspc monitor LVDS-0 -d VI VII VIII IX X
	else
		bspc monitor LVDS-0 -d I II III IV V VI VII VIII IX X
	fi


bspc rule -a Guake floating=on
bspc rule -a galculator floating=on
bspc rule -a gpick floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
